### ISSUE TITLE
Window buttons broken in KDE plasma

### ISSUE THREAD

**Issue by Aloso** [epilys/gerb#34]
**Describe the bug**
See screenshot; the close button at the top right looks weird. The minimize/maximize buttons also look weird when the mouse is hovering them.

**To Reproduce**
Open gerb

**Expected behavior**
Buttons look normal, and ideally follow the system-wide theme.

**Screenshots**
![gerb_window](https://user-images.githubusercontent.com/15658558/227010447-05ecd2ea-ee51-49e6-9a24-46b8f83bb28d.png)

On this screenshot you can see gerb with the weird close button. It also shows the KDE system settings and a GTK app, which use the system's theme "Breeze dark". Gerb uses a different, light theme.

![gerb_hover](https://user-images.githubusercontent.com/15658558/227011871-60f3ed4f-8e2d-4b7b-bb23-e89259e8e442.png)

On this screenshot, I hovered the "maximize" window button.

**(please complete the following information):**

- OS: Manjaro Linux 22.0.5
  - Kernel: x86_64 Linux 5.15.102-1-MANJARO
  - DE: KDE 5.103.0 / Plasma 5.26.5

- `gerb` version/commit: ``not included if built without `build-info` feature``
  - gerb was downloaded from [this releases page](https://github.com/epilys/gerb/releases/tag/v0.0.1-alpha%2B2023-03-22). You should consider enabling the `build-info` feature in CI.

**Comment by Aloso** [comment]
@epilys yes, switching to the system theme works, and then the window buttons look normal.

Unfortunately, when enabling the system theme, some text becomes unreadable.

**Comment by epilys** [comment]
@Aloso I found this: do you think it's relevant?

https://gitlab.gnome.org/GNOME/gtk/-/issues/3283

**Comment by Aloso** [comment]
@epilys yes, that looks exactly like the bug I found. Since it appears to be a KDE Plasma or GTK bug, feel free to close this issue.
