### ISSUE TITLE
Merged on pkgsrc/NetBSD

### ISSUE THREAD

**Issue by 0323pin** [epilys/gerb#41]
As discussed on reddit, I've now imported the package into the main pkgsrc branch, http://mail-index.netbsd.org/pkgsrc-changes/2023/03/29/msg271500.html

Regards,
pin

**Comment by epilys** [comment]
great work! I will add it to the README and also put this badge on top: (I assume the pkgsrc.se url will become valid once it syncs the new commits?

[![netbsd](https://img.shields.io/badge/netbsd-pkgsrc%2Ffonts%2Fgerb-9cf)](https://pkgsrc.se/fonts/gerb)

**Comment by 0323pin** [comment]
> I assume the pkgsrc.se url will become valid once it syncs

Yes, it's [there now](https://pkgsrc.se/fonts/gerb)

Thanks for the badge.
