### ISSUE TITLE
Implement saving modifications to disk

### ISSUE THREAD

**Issue by epilys** [epilys/gerb#5]

**Comment by ctrlcctrlv** [comment]
If you use glifparser as I mentioned in #11 you should be able to solve this pretty easily.

![image](https://user-images.githubusercontent.com/838783/215997711-0a776059-17dc-4c0e-aa24-a41d5f333b52.png)

I've tested in/out of .glif XML pretty heavily.

**Comment by epilys** [comment]
@ctrlcctrlv thanks! Will surely check it out
